name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg

      - name: Push Snake to GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generate snake"
          git push
